apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus   # <-- 🔥 Important!! Set UID here
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    orgId: 1
    editable: true
